name: 'Runs gdlint on GDScript Code'
description: 'Runs gdlint on all GDScript Code in a repository.'
inputs:
  python:
    description: |
      Install Python
      Default is true.
    default: true
  python_version:
    description: |
      Install a specific python version
      Default is 3.10.
    default: true
  gdtoolkit_version:
    description: |
      Install a specific gdtoolkit version
      Default is latest.
    default: 'latest'
  directory:
    description: |
      Define on which directory gdlint should be run.
      Please provide a directory name without trailing /.
      Default is all files in the root of the repository.
    default: false

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.python  == 'true' }}
      name: Setup Python
      uses: actions/setup-python@v5.1.1
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: '3.10' # optional
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - if: ${{ inputs.gdtoolkit_version  == 'latest' }}
      name: Install gdtoolkit
      shell: bash
      run: |
        pip install gdtoolkit
    - if: ${{ inputs.gdtoolkit_version  != 'latest' }}
      name: Install gdtoolkit
      shell: bash
      run: |
        pip install gdtoolkit==${{ inputs.gdtoolkit_version }}
    - if: ${{ inputs.directory  == 'false' }}
      name: Run gdlint
      shell: bash
      run: |
        gdlint *.gd
    - if: ${{ inputs.directory  != 'false' }}
      name: Run gdlint
      shell: bash
      run: |
        gdlint ${{ inputs.directory }}/*.gd
