name: Run tests on gdlint workflow
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Test action with default values
        uses: ./
      - name: Test action with defined directory green
        uses: ./
        with:
          directory: test/green
        

